Project Structure
obernardovieira/POS-System pull request #25
Opened 2019-01-19 18:25 UTC by obernardovieira

This code was written by me a very long time ago. I never worked professionally with python, so I'm not very proficient as I would like to.

In this PR I decided to change the structure, putting everything on the same page and also fixed some naming to a better normalization.

2019-01-19 20:36 UTC, JeanCarlosChavarriaHughes commented on README.md
> +All the workers are registered on the system, and when someone start to work, needs to login in his account and logout at the end.
someone starts

2019-01-19 20:38 UTC, JeanCarlosChavarriaHughes commented on README.md
> +The system load from a database what is still available and what's not available. When someting's stock is almost ending, the user will be warned.
The system loads ...
When something in the stock is ...

2019-01-19 20:44 UTC, JeanCarlosChavarriaHughes requested changes

2019-01-19 20:44 UTC, JeanCarlosChavarriaHughes commented on README.md
> +The administrator will take care of the available itens.
available items.

2019-01-19 20:44 UTC, JeanCarlosChavarriaHughes commented on README.md
> +The administrator as a panel to manage accounts in the system. Each employer have a card with a username and a password.
Each employee has

2019-01-21 09:23 UTC, obernardovieira commented
@JeanCarlosChavarriaHughes thanks.
Since your comments were mostly around README file and I was planning to update it, please have a look at #26

2019-01-21 12:59 UTC, JeanCarlosChavarriaHughes commented
Nice. #26  and #25 are ready for merge.

2019-01-21 15:57 UTC, merged